import turtle as t
from random import randint
t.color('black')

def couleur_aleatoire():
  t.colormode(255)
  r = randint(0, 255)
  g = randint(0, 255)
  b = randint(0, 255)
  return (r, g, b)

def car():
  longueur = randint(100,150)
  decapotable = randint(25,45)
  t.pendown()
  t.color("black")
  t.fillcolor(couleur_aleatoire())
  t.begin_fill()
  t.setheading(00)
  t.forward(longueur)
  t.right(90)
  t.forward(20)
  t.right(90)
  t.forward(longueur)
  t.right(90)
  t.forward(20)
  t.right(90)
  t.end_fill()
  t.penup()
  t.forward(20)
  t.left(decapotable)
  t.pendown()
  t.fillcolor("lightblue")
  t.begin_fill()
  t.forward(30)
  t.right(decapotable)
  t.forward(30)
  t.right(decapotable)
  t.forward(30)
  t.end_fill()
  t.penup()
  t.setheading(0)
  t.backward(40)
  t.pendown()
  t.setheading(90)
  t.forward(decapotable/2)
  t.penup()
  t.backward(round(decapotable/2)+3)
  t.setheading(0)
  t.backward(40)
  t.setheading(-90)
  t.forward(20)
  t.pendown()
  t.fillcolor("black")
  t.begin_fill()
  t.circle(10)
  t.end_fill()
  t.penup()
  t.setheading(0)
  t.forward(55)
  t.setheading(-90)
  t.fillcolor("black")
  t.begin_fill()
  t.circle(10)
  t.end_fill()
  t.setheading(0)
  t.backward(longueur-50)
  t.setheading(90)
  t.forward(23)
car()